#!/usr/bin/env bash
# ponytail: one script beats copy-pasting three terraform outputs
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE="${1:-../.env}"
REGION=$(terraform output -raw aws_region)
SNS=$(terraform output -raw sns_topic_arn)
PAYMENT=$(terraform output -raw sqs_payment_url)
NOTIFY=$(terraform output -raw sqs_notify_url)

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source <(grep -E '^(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)=' "$ENV_FILE" 2>/dev/null || true)
fi

cat >"$ENV_FILE" <<EOF
# Generated by infra/write-env.sh — add your AWS credentials below if missing

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-your_key_here}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-your_secret_here}
AWS_DEFAULT_REGION=${REGION}

SNS_TOPIC_ARN=${SNS}
SQS_PAYMENT_URL=${PAYMENT}
SQS_NOTIFY_URL=${NOTIFY}
EOF

echo "Wrote ${ENV_FILE}"
